# tests/telem/Makefile -- host unit tests for lib/telem (see tests/host.mk).
MODULE    := telem
SRCS      := ../../lib/telem/telem.c ../../lib/telem/ring.c ../../lib/telem/health.c
TEST_SRCS := test_telem.c
INCLUDES  := -I../../lib/telem -I..
include ../host.mk
